### ISSUE TITLE
headless argument for Edge driver

### ISSUE THREAD

**Issue by brandyndauch** [atata-framework/atata-configuration-json#43]
Hello Yevgeniy,

Hopefully this is a quick question, but I'm trying to pass a headless argument in my .json file. I've tried `headless` and `--headless` but nothing seems to running my edge driver in headless mode. Package I'm using is Selenium.WebDriver.MSEdgeDriver. Thanks for the help!

**Comment by YevgeniyShunevych** [comment]
Hello @brandyndauch,

Unfortunately, it is not very easy to do, currently. But possible.

The problem is that support of headless Edge mode appeared in new Chromium-based Edge. And in order to use it with WebDriver, you need latest alpha version of `Selenium.WebDriver` (4.0.0-alpha05 at the moment). WebDriver 3 does not contain needed configuration options. And `Atata.Configuration.Json` currently supports only WebDriver 3 configuration. I am going to support WebDriver 4 after its release. Until then there is a workaround.

Please also check out [Use WebDriver (Chromium) for test automation](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium?tabs=c-sharp) article.

I have created [Headless Edge](https://github.com/atata-framework/atata-samples/tree/master/HeadlessEdge) sample project that runs Edge in headless mode. Please check out its sources. The only moment is that it configures Edge driver in build time, without JSON config (I hope that this is not a big issue for you):

```cs
AtataContext.Configure().
    UseDriver(() =>
    {
        EdgeOptions options = new EdgeOptions
        {
            UseChromium = true
        };

        options.AddArguments("headless", "disable-gpu", "window-size=1024,768");

        return new EdgeDriver(AppDomain.CurrentDomain.BaseDirectory, options);
    }).
```

**Comment by brandyndauch** [comment]
The work around is perfect! I'll keep an eye out of the new release. Thank you for the help!
